apiVersion: apps/v1
kind: Deployment
metadata:
    name: employees-webapp-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: employees-webapp
    template:
        metadata:
            labels:
                component: employees-webapp
        spec:
            containers:
                - name: employees-webapp
                  image: mmbarek/employees-webapp
                  ports:
                    - containerPort: 80
                  env:
                    - name: PROJECTS_API_URL
                      # The request to REST API is coming from Browser
                      # so we can't use an internal URL. To be upated if the minikube IP changes
                      value: http://172.17.52.21/services/pms                   